# Generated by Django 3.2.9 on 2021-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestudies', '0002_auto_20211115_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
